In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
print("Pandas version: ",pd.__version__)

Pandas version:  3.0.2

In [4]:
print("Numpy version:",np.__version__)

Numpy version: 2.2.4

In [5]:
data = {
    "Name": ["Barney", "Lily", "Marshall", "Robin", "Ted"],
    "Dept.": ["Sales", "Education", "Law", "Media & Entertainment", "Architecture"],
    "Salary": [110000, 36000, 700000, 55000, 42000],
    "Experience": [7,5,3,9,6]
}

In [6]:
df = pd.DataFrame(data)

In [7]:
df

       Name                  Dept.  Salary  Experience
0    Barney                  Sales  110000           7
1      Lily              Education   36000           5
2  Marshall                    Law  700000           3
3     Robin  Media & Entertainment   55000           9
4       Ted           Architecture   42000           6

In [8]:
print("Shape", df.shape)

Shape (5, 4)

In [9]:
print("Columns", df.columns.tolist())

Columns ['Name', 'Dept.', 'Salary', 'Experience']

In [10]:
print("\nData Types", df.dtypes)

Data Types Name            str
Dept.           str
Salary        int64
Experience    int64
dtype: object

In [11]:
print("\nBasic Statistics", df.describe())

Basic Statistics               Salary  Experience
count       5.000000    5.000000
mean   188600.000000    6.000000
std    287373.972377    2.236068
min     36000.000000    3.000000
25%     42000.000000    5.000000
50%     55000.000000    6.000000
75%    110000.000000    7.000000
max    700000.000000    9.000000

In [15]:
print("\nSalary Column\n", df["Salary"])

Salary Column
 0    110000
1     36000
2    700000
3     55000
4     42000
Name: Salary, dtype: int64

In [16]:
print("Name and Salary\n", df[["Name", "Salary"]])

Name and Salary
        Name  Salary
0    Barney  110000
1      Lily   36000
2  Marshall  700000
3     Robin   55000
4       Ted   42000

In [17]:
high_earners = df[df["Salary"]>50000]

In [18]:
high_earners

       Name                  Dept.  Salary  Experience
0    Barney                  Sales  110000           7
2  Marshall                    Law  700000           3
3     Robin  Media & Entertainment   55000           9

In [19]:
exps = df[df["Experience"]>4]

In [20]:
exps

     Name                  Dept.  Salary  Experience
0  Barney                  Sales  110000           7
1    Lily              Education   36000           5
3   Robin  Media & Entertainment   55000           9
4     Ted           Architecture   42000           6

In [22]:
df[(df["Salary"]>50000) & (df["Experience"]>4)]

     Name                  Dept.  Salary  Experience
0  Barney                  Sales  110000           7
3   Robin  Media & Entertainment   55000           9

In [23]:
df[(df["Salary"]>50000) | (df["Experience"]>4)]

       Name                  Dept.  Salary  Experience
0    Barney                  Sales  110000           7
1      Lily              Education   36000           5
2  Marshall                    Law  700000           3
3     Robin  Media & Entertainment   55000           9
4       Ted           Architecture   42000           6

In [24]:
df.groupby("Dept.")["Salary"].mean()

Dept.
Architecture              42000.0
Education                 36000.0
Law                      700000.0
Media & Entertainment     55000.0
Sales                    110000.0
Name: Salary, dtype: float64

In [25]:
df.groupby("Dept.")["Salary"].max()

Dept.
Architecture              42000
Education                 36000
Law                      700000
Media & Entertainment     55000
Sales                    110000
Name: Salary, dtype: int64

In [26]:
df.groupby("Dept.")["Salary"].sum()

Dept.
Architecture              42000
Education                 36000
Law                      700000
Media & Entertainment     55000
Sales                    110000
Name: Salary, dtype: int64

In [27]:
df.groupby("Dept.")["Salary"].count()

Dept.
Architecture             1
Education                1
Law                      1
Media & Entertainment    1
Sales                    1
Name: Salary, dtype: int64

In [28]:
df.groupby("Dept.")["Experience"].mean()

Dept.
Architecture             6.0
Education                5.0
Law                      3.0
Media & Entertainment    9.0
Sales                    7.0
Name: Experience, dtype: float64

In [29]:
df.sort_values('Salary')

       Name                  Dept.  Salary  Experience
1      Lily              Education   36000           5
4       Ted           Architecture   42000           6
3     Robin  Media & Entertainment   55000           9
0    Barney                  Sales  110000           7
2  Marshall                    Law  700000           3

In [30]:
df.sort_values('Salary', ascending=False)

       Name                  Dept.  Salary  Experience
2  Marshall                    Law  700000           3
0    Barney                  Sales  110000           7
3     Robin  Media & Entertainment   55000           9
4       Ted           Architecture   42000           6
1      Lily              Education   36000           5

In [31]:
df.sort_values('Experience', ascending=True)

       Name                  Dept.  Salary  Experience
2  Marshall                    Law  700000           3
1      Lily              Education   36000           5
4       Ted           Architecture   42000           6
0    Barney                  Sales  110000           7
3     Robin  Media & Entertainment   55000           9

In [32]:
df.sort_values('Experience', ascending=False)

       Name                  Dept.  Salary  Experience
3     Robin  Media & Entertainment   55000           9
0    Barney                  Sales  110000           7
4       Ted           Architecture   42000           6
1      Lily              Education   36000           5
2  Marshall                    Law  700000           3

In [37]:
df[df['Salary']>40000].sort_values('Experience', ascending=False)

       Name                  Dept.  Salary  Experience
3     Robin  Media & Entertainment   55000           9
0    Barney                  Sales  110000           7
4       Ted           Architecture   42000           6
2  Marshall                    Law  700000           3